### ISSUE TITLE
transpartent not working

### ISSUE THREAD

**Issue by ryannewcomer** [TheBigWazz/ZenThemes#3]
## hi

i just put your twilight `userChrome.css` file in my chrome folder and installed all mod with corrects config. But the new tab transparent doesn't seem to be working. It is with my 'mica for everyone' config?

here is a little video

https://github.com/user-attachments/assets/b4ead504-af19-42d9-b3b1-646e1ca729ad

as you can see, the transparent work when a webpage is loading, but it don't work on new tab

I am on the latest twilight version

Thanks

**Comment by ryannewcomer** [comment]
my current userChrome.css:

```css
/* makes the browser transparent*/
#navigator-toolbox{
    background-color:rgba(0,0,0,0) !important;
  }
  
  /* window controls shadowing fix by @taroj1205 */
  #zen-sidebar-splitter {
    opacity: 1 !important;
    border: none !important;
    min-width: 0 !important;
    width: 6px !important;
    height: 0.1% !important;
  }
  
  &:has(#zen-sidebar-splitter:hover) #zen-sidebar-splitter,
  #zen-sidebar-splitter:hover:active {
    width: 6px !important;
    height: 100% !important;
  }
  
  /* --- Integrated URL Bar --- */
  
  /* Webview Styles */
  @media not (-moz-bool-pref:"zen.view.compact") {
    #browser { 
      --urlbar-min-width: 28px !important;
    }
  
    /* Nav bar style and transparency level */
    #nav-bar {
      --zen-toolbar-height: 45px;
      background-color: rgba(0, 0, 0, 0.2) !important;
      border-radius: 10px 10px 0 0 !important;
      padding-left: 6px !important;
      margin: 6px 6px 0 1px !important;
      box-shadow : none !important;
    }
   }
  
    /* Browser transparency level */
    .browserSidebarContainer {
      background-color: rgba(0, 0, 0, 0.21) !important;
      border-radius: 0px 0px 10px 10px !important;
      margin-top: 0px !important;
      margin-right: 0px !important;
      box-shadow : none !important;
    }
    
    /* Toolbar spacing */
    #navigator-toolbox {
      padding-top: 8px !important;
    }
  
  
  #zen-workspaces-button {
    background-color: rgba(255, 255, 255, 0.04) !important;
    box-shadow: 0px 1px 10px rgba(0,0,0,0.1) !important;
    border-radius: 8px !important;
    border: 1px solid #ffffff0c !important;
  }  
  
  #zen-workspaces-button {
    .subviewbutton {
        &[active="true"] {
            background: rgba(255, 255, 255, 0.1) !important;
            transition: 0.3s !important;
            border: 1px solid #ffffff0a !important;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.062) !important;
  
        }
  
        &:hover {
            background: rgba(255, 255, 255, 0.2) !important;
            transition: 0.3s !important;
        }
  
        &:after {
            display: none !important;
        }
  
    }
  }
  
  #zen-current-workspace-indicator {
      padding: 10px calc(4px + var(--tab-inline-padding)) !important;
      font-weight: 500 !important; 
  }
  
  /* --- URL Bar Loading Highlight (By: CandleBob on Discord) --- */
  #nav-bar {
      #urlbar:not([breakout-extend="true"]) #urlbar-background::before {
          content: '';
          position: absolute;
          inset: 0;
          background: linear-gradient(25deg, #4e4ac233, #4ecdc433, #4e4ac233);
          background-size: 200% 100%;
          animation: urlbar-loading-gradient 1s linear reverse infinite;
          animation-play-state: paused;
          opacity: 0;
          transition: opacity 0.25s;
      }
  
      &:has(#reload-button[displaystop="true"]) #urlbar-background::before {
          animation-play-state: running;
          opacity: 1;
      }
  }
  
  @keyframes urlbar-loading-gradient {
      0% { background-position: 0% 0%; }
      100% { background-position: 200% 0%; }
  }
  
  /* --- Mini Container in URL --- */
  @-moz-document url-prefix('chrome://') {
      #urlbar-container #page-action-buttons #userContext-icons {
          position: relative;
          order: 2;
          height: 8px;
          width: 8px;
          background-color: var(--identity-icon-color);
          border-radius: 32px;
          margin-left: 12px !important;
  
          & image,
          & label {
              display: none;
          }
      }
  }
  
  /* --- Hide the Workspace Indicator --- */
  #zen-current-workspace-indicator {
      display: none !important;
  }
  
  .tab-reset-button {
     display: none !important;
  }
  
  tab-group {
    display: grid !important;
    background: color-mix(in srgb, var(--tab-group-color-invert) 10%, transparent) !important;
    border-radius: var(--border-radius-medium);
    margin-bottom: 4px;
    margin-inline: 2px !important;
    border: 2px solid color-mix(in srgb, var(--tab-group-color-invert) 10%, transparent);
    padding: 5px 0px !important;
    max-height: 1000px !important;
    transition: max-height 0.2s ease !important;
  
    & tab {
      transition: opacity 0.5s ease !important;
    }
  
    &>vbox {
      padding-top: 2px !important;
    }
  
    & .tab-group-label-container {
      &:after {
        display: none !important;
      }
  
      &>label {
        background: transparent !important;
        border: unset !important;
        font-weight: 500 !important;
        text-align: unset !important;
        color: var(--sidebar-text-color) !important;
        padding-left: 25px !important;
      }
      &>label::before {
        content: "" !important;
        position: absolute !important;
        left: 5px !important;
        top: 50% !important;
        transform: translateY(-50%) !important;
        width: 16px !important;
        height: 16px !important;
        background-color: var(--sidebar-text-color);
        mask-image: url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjAgOS41MDJWOC43NWEyLjI1IDIuMjUgMCAwIDAtMi4yNS0yLjI1aC01LjcyNWwtMi4zOC0xLjk4QTIuMjUgMi4yNSAwIDAgMCA4LjIwNCA0SDQuMjVBMi4yNSAyLjI1IDAgMCAwIDIgNi4yNWwtLjAwNCAxMS41QTIuMjUgMi4yNSAwIDAgMCA0LjI0NiAyMEgxOC40N2ExLjc1IDEuNzUgMCAwIDAgMS42OTgtMS4zMjVsMS43NS02Ljk5OGExLjc1IDEuNzUgMCAwIDAtMS42OTgtMi4xNzVIMjBaTTQuMjUgNS41aDMuOTU2YS43NS43NSAwIDAgMSAuNDguMTczbDIuNTg4IDIuMTU0YS43NS43NSAwIDAgMCAuNDguMTczaDUuOTk2YS43NS43NSAwIDAgMSAuNzUuNzV2Ljc1Mkg2LjQyNGEyLjI1IDIuMjUgMCAwIDAtMi4xODMgMS43MDRsLS43NDQgMi45NzhMMy41IDYuMjVhLjc1Ljc1IDAgMCAxIC43NS0uNzVabTEuNDQ3IDYuMDdhLjc1Ljc1IDAgMCAxIC43MjctLjU2OEgyMC4yMmEuMjUuMjUgMCAwIDEgLjI0Mi4zMWwtMS43NSA2Ljk5OWEuMjUuMjUgMCAwIDEtLjI0Mi4xODlINC4yODVhLjI1LjI1IDAgMCAxLS4yNDMtLjMxbDEuNjU1LTYuNjJaIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+');
        mask-size: contain;
        mask-repeat: no-repeat;
        background-size: contain !important;
        background-repeat: no-repeat !important;
    }
    }
  
    &[collapsed] {
      overflow: hidden !important;
      max-height: 3rem !important;
  
      & tab {
        opacity: 0 !important;
      }
      & .tab-group-label-container > label {
        background: transparent !important;
        border: unset !important;
        font-weight: 500 !important;
        text-align: unset !important;
        color: var(--sidebar-text-color) !important;
        padding-left: 25px !important;
      }
      & .tab-group-label-container > label::before {
        content: "" !important;
        position: absolute !important;
        left: 5px !important;
        top: 50% !important;
        transform: translateY(-50%) !important;
        width: 16px !important;
        height: 16px !important;
        background-color: var(--sidebar-text-color);
        mask-image: url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOC4yMDcgNGMuNDYgMCAuOTA4LjE0MSAxLjI4NC40MDJsLjE1Ni4xMkwxMi4wMjIgNi41aDcuNzI4YTIuMjUgMi4yNSAwIDAgMSAyLjIyOSAxLjkzOGwuMDE2LjE1OC4wMDUuMTU0djlhMi4yNSAyLjI1IDAgMCAxLTIuMDk2IDIuMjQ1TDE5Ljc1IDIwSDQuMjVhMi4yNSAyLjI1IDAgMCAxLTIuMjQ1LTIuMDk2TDIgMTcuNzVWNi4yNWEyLjI1IDIuMjUgMCAwIDEgMi4wOTYtMi4yNDVMNC4yNSA0aDMuOTU3Wm0xLjQ0IDUuOTc5YTIuMjUgMi4yNSAwIDAgMS0xLjI0NC41MTJsLS4xOTYuMDA5LTQuNzA3LS4wMDF2Ny4yNTFjMCAuMzguMjgyLjY5NC42NDguNzQzbC4xMDIuMDA3aDE1LjVhLjc1Ljc1IDAgMCAwIC43NDMtLjY0OGwuMDA3LS4xMDJ2LTlhLjc1Ljc1IDAgMCAwLS42NDgtLjc0M0wxOS43NSA4aC03LjcyOUw5LjY0NyA5Ljk3OVpNOC4yMDcgNS41SDQuMjVhLjc1Ljc1IDAgMCAwLS43NDMuNjQ4TDMuNSA2LjI1djIuNzQ5TDguMjA3IDlhLjc1Ljc1IDAgMCAwIC4zOTUtLjExM2wuMDg1LS4wNiAxLjg5MS0xLjU3OC0xLjg5LTEuNTc1YS43NS43NSAwIDAgMC0uMzc3LS4xNjdMOC4yMDcgNS41WiIgZmlsbD0iIzAwMDAwMCIvPjwvc3ZnPg==');
        mask-size: contain;
        mask-repeat: no-repeat;
        background-size: contain !important;
        background-repeat: no-repeat !important;
    }
    }
  }
  tab-group:has(tab[hidden]){
    display: none !important;
  }

  #zen-essentials-container {
    margin-top: auto !important; /* Push container to the bottom of the layout */
    order: 999 !important; /* Ensure it's the last element in flex/grid layout */
    overflow: hidden !important;
    transition: max-height 0.3s ease-out !important; /* Smooth height transitions */
    opacity: 1 !important;
    
    /* Responsive grid layout for pinned tabs/items */
    grid-template-columns: repeat(auto-fit, minmax(var(--tab-pinned-min-width-expanded), auto)) !important;
    
    /* Scroll handling */
    overflow-y: auto !important;
    overflow-x: hidden !important;
    scrollbar-width: thin !important; /* Slim scrollbar */
    
    display: grid !important;
    padding: 0 0 5px !important;
    border-top: none !important; 
}
```
